/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DialogContent: typeof import('./src/components/dialog-content/DialogContent.vue')['default']
    EditTask: typeof import('./src/components/edit-task/EditTask.vue')['default']
    FilterProjectByStatus: typeof import('./src/components/filter-projects-by-status/FilterProjectByStatus.vue')['default']
    NewProject: typeof import('./src/components/new-project/NewProject.vue')['default']
    NewTask: typeof import('./src/components/new-task/NewTask.vue')['default']
    ProjectForm: typeof import('./src/components/new-project/ProjectForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskForm: typeof import('./src/components/new-task/TaskForm.vue')['default']
    Typography: typeof import('./src/components/Typography.vue')['default']
  }
}
