/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/project-page/components/Board': RouteRecordInfo<'/project-page/components/Board', '/project-page/components/Board', Record<never, never>, Record<never, never>>,
    '/project-page/components/ProjectHome': RouteRecordInfo<'/project-page/components/ProjectHome', '/project-page/components/ProjectHome', Record<never, never>, Record<never, never>>,
    '/project-page/components/Task': RouteRecordInfo<'/project-page/components/Task', '/project-page/components/Task', Record<never, never>, Record<never, never>>,
    '/project-page/Project': RouteRecordInfo<'/project-page/Project', '/project-page/Project', Record<never, never>, Record<never, never>>,
  }
}
